[[language]]
auto-format = false
comment-tokens = ";"
file-types = ["pio"]
language-servers = ["piolsp"]
name = "pio"
scope = "source.pio"

[language-server.piolsp]
args = [
  "--pioasm",
  "pioasm",
  "--logfile",
  "/tmp/piolsp.log",
  "--verbose",
]
command = "./target/debug/piolsp2"
