name: "Test"
on:
  pull_request:
      paths:
      - src/**
      - tests/**
      - Cargo.toml
      - Cargo.lock
  push:
      paths:
      - src/**
      - tests/**
      - Cargo.toml
      - Cargo.lock
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build
    - run: ./result/bin/piolsp --version
